### ISSUE TITLE
git hook 중에 pre-commit 이 동작하지 않음

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#10]
`git commit` 명령을 실행하면 다음과 같은 메시지가 나타납니다.

```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

실제로 pre-commit에서 지정한 prettier 명령이 실행되지 않는데요, 관련 내용으로 검색 해 보니 해당 훅을 정의한 파일에 권한을 주면 된다고 합니다.(ex) chmod 명령어로 권한 주기)

그런데 이 문제가 왜 발생했을까 생각 해 보면 아마도 파일을 직접 생성했기 때문인 것 같습니다. #4 작업 시 husky 라이브러리의 사용 방법(`npx husky add .husky/pre-commit ...`)에 의존하지 않고 직접 해당 경로에 파일을 생성 하셨었는지요?

관리자 모드가 아닌 채로 파일을 직접 생성했다면 이런 권한 관련 문제로 스크립트 파일의 실행이 안 될 수 있을 것 같네요.

**Comment by jiyeon2** [comment]
>그런데 이 문제가 왜 발생했을까 생각 해 보면 아마도 파일을 직접 생성했기 때문인 것 같습니다. https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/4 작업 시 husky 라이브러리의 사용 방법(npx husky add .husky/pre-commit ...)에 의존하지 않고 직접 해당 경로에 파일을 생성 하셨었는지요?

네 상연님의 말씀이 맞습니다! 
pre-commit 파일의 경우 상연님께 받은 파일을 직접 .husky폴더에 넣었습니다

이런 문제가 있는지 몰랐네요!
husky 라이브러리의 사용 방법을 확인하고 다시 설정해보겠습니다!

**Comment by jiyeon2** [comment]
#20 으로 수정하였습니다
