### ISSUE TITLE
Habit 인터페이스의 days를 좀 더 명확히 표현할 수 있을까요?

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#12]
현재는 아래와 같습니다.

```
export interface Habit {
  id: number;
  name: string;
  description: string;
  days: Day[]; // 특정 요일에만 진행하는 경우
}

export type Day = '월' | '화' | '수' | '목' | '금' | '토' | '일';
```

이때 days 속성에 '월' 이 여러 번 들어가도 문제가 되지 않습니다.

저는 이것을 바로잡아보고 싶었는데.. 이게 잘 안되더라고요.

어떻게 수정 할 수 있을까요? 그 전에 수정하는 것이 필요하다고 생각하시나요?

**Comment by jiyeon2** [comment]
Day[] 형태로는 days에 '월'이 여러번 들어가는 걸 막지 못하는 게 맞기는 하네요!

days 부분은 특정 일자에 각 습관 실행 여부 체크 기능 #2과 관련있다고 생각해서
저는 아직 진행을 하지 않았는데
어떤 경우에 '월'이 여러번 들어가는 경우가 생기나요??

바로잡으려다가 잘 안되었다고 하셨는데
혹시 어떤 방식을 시도하셨는지도 알려주실 수 있으실까요??

지금 당장 생각나는 것으로는
`days = [...Set(['월','월','화'])]` 이런식으로 set으로 중복을 없애고 배열형태로 저장하는 방식밖에 없네요..

**Comment by jiyeon2** [comment]
unique array를 유틸리티 타입으로 만들 수도 있는거 같아요!
https://stackoverflow.com/questions/57016728/is-there-a-way-to-define-type-for-array-with-unique-items-in-typescript
아직 이해는 잘 못했지만 스택오버플로에 올라온 답변 글 링크를 남깁니다

**Comment by greyHairChooseLife** [comment]
>어떤 경우에 '월'이 여러번 들어가는 경우가 생기나요??

체크박스를 check했다가 unchecked했다가.. 이렇게 하면 자꾸 쌓입니다. 지연님이 예시 들어주신 것 같은 관련 된 처리를 해 주지 않으면요.


>바로잡으려다가 잘 안되었다고 하셨는데
혹시 어떤 방식을 시도하셨는지도 알려주실 수 있으실까요??

공유 할 것도 없는게 그냥 util타입에 뭐 없나 하고 이것저것 되도않는 시도 해 본것들이에요 ㅋㅋㅋ

--- 

days타입의 표현력을 좀 더 올릴 수 없을까 하던 생각이었는데, 

링크 주신 것 보니까... 배보다 배꼽이 더 큰 것 같습니다.. ㅎㅎ 이 부분은 개인적으로 뭔가 손대보던가 하는게 좋을 것 같아요.

**Comment by jiyeon2** [comment]
예시 정도의 커스텀 유틸리티 타입을 만들어 쓸 만큼 능숙하진 못해서
저도 개인적으로 공부를 좀 더 해보겠습니다!
