### ISSUE TITLE
docs 이슈 라벨 추가

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#24]
Wiki에 이슈 라벨 사용법을 추가하고 나니까 이제 맘대로 이슈 라벨을 추가하기가 조심스러워지네요. :baby_chick: 

앞으로도 코드 컨벤션이나 기타 팀이 공유해야 하는 내용을 위키에 공유하면 좋을 것 같은데요, 

이것도 맘대로 쓰기가 좀 그래서 여기에 뭔가 추가 할 내용이 생기면 `docs` 라벨을 달고 이슈에 올려서 논의하고 추가하는 것이 어떨까요?

**Comment by jiyeon2** [comment]
docs 라벨 괜찮네요! 
코드나 기능과 연관이 적지만
프로젝트 관련 공유사항이나 README 관련된 내용을 논의하고 싶은 경우 
docs 라벨로 처리하면 좋겠어요!

**Comment by jiyeon2** [comment]
아니면 코드와 관련없는 팀 내부 규칙등은 discussion 탭을 활용해봐도 괜찮을거같아요!

issue를 discussion으로 변경하거나
discussion에서 issue를 생성하는 것도 가능한듯 합니다

**Comment by greyHairChooseLife** [comment]
@jiyeon2 `코드와 관련 없는` vs `있는` 이라는 기준이 혹시 

`개발하려는 프로그램 관련` vs `개발(협업) 프로세스 관련` 으로 명확히 표현 되는 걸까요? 아니면 다른 의미가 더 있을까요.

예를 들면 _"제작자에게 이메일 보내는 기능을 추가하자"_ 라고 제안 하려한다면 issue 와 discussion 중 무엇에 들어가야 할까요?

**Comment by jiyeon2** [comment]
> `개발하려는 프로그램 관련` vs `개발(협업) 프로세스 관련` 으로 명확히 표현 되는 걸까요? 

제가 말씀드리고 싶었던 게 상연님이 정리해주신 이 내용입니다!

> 예를 들면 _"제작자에게 이메일 보내는 기능을 추가하자"_ 라고 제안 하려한다면 issue 와 discussion 중 무엇에 들어가야 할까요?

이런 경우
지금 코드상에는 제작자에게 이메일을 보내는 기능과 관련된 코드가 없으니 discussion에서 논의하고 
구체화된 기능을 todo 라벨을 단 issue로 생성하면 어떨까 싶습니다

만약 제작자에게 이메일 보내는 기능이 이미 코드로 구현되어 있는 상황에서
해당 기능에 버그를 발견하면 issue로 제보하고

해당 기능을 개선할 아이디어가 있다면 discussion에서 idea를 생성하여 논의하고 
추가기능이 확정되면 todo 라벨을 단 issue를 생성하는 방식을 생각했는데

다른분들은 어떻게 생각하시는지 궁금합니다~

**Comment by greyHairChooseLife** [comment]
@jiyeon2 
어.. 근데 `개발하려는 프로그램 관련` vs `개발(협업) 프로세스 관련`으로 나눈다면 제가 예시로 든 물음은 전자에 해당하지 않을까요? 개발 하려는 프로그램의 기능에 관한 거니까요.

말씀 하신 대로라면, 
:x: `개발하려는 프로그램 관련` vs `개발(협업) 프로세스 관련`
:o: `discussion을 통해 개발 하기로 확정 한 내용 and 이미 코드로 표현 된 모든 내용들` vs `아직 확정 되지 않은 모든 것들`

이렇게 구분하자는 것 같은데요. 제가 지연님 생각을 제대로 이해 한 것이 맞을까요?

**Comment by jiyeon2** [comment]
죄송합니다 제가 상연님이 쓰신 걸 제가 읽고싶은 대로 읽고 답변드렸어요..
혼란스럽게 해서 죄송합니다

제 기준은

프로젝트 ’코드‘에 변경사항이
생기는 작업 논의는 이슈탭

코드 변경사항이 없는 협업 프로세스 수정, 아이디어 제시 등은 discussion탭
이었습니다!

**Comment by greyHairChooseLife** [comment]
기존에 없던 추가 기능을 만들고 싶다면,

1. `discussion`에 제안
2. 제안이 구체화되고 개발 여부가 확정 되면 `issue`에 `TODO` 라벨 달고 등록

을 말씀하시는 건가요?

bug는 이미 코드에 존재하는 것일테니까, 

아래처럼 하면 정리가 될까요?

1. 코드에 없는 새로운 기능 : `discussion` :point_right: (구체화 및 개발 확정 시) :point_right: `issue: TODO라벨` :point_right: `project: Todo`
2. 코드에 있는 기능 수정 및 버그 : `issue` :point_right: (이슈에서 논의 후 결정 되는 대로) :point_right: `project: Todo`
3. 협업 프로세스(기존에 있든, 없든) : `(추가/수정)discussion` :point_right: (구체화 및 확정 시) :point_right: `wiki`
