### ISSUE TITLE
merge commit 메시지 컨벤션을 제안 드려봐요.

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#25]
## mege commit 메시지란

merge 자체도 하나의 commit이 발생합니다. 기본적으로 다음과 같이 생성 돼요.
- 로컬에서 작업 시 (fast forward는 merge commit 생략됨(default))
:point_right:  `Merge branch [브랜치 이름]`
- pr 승인을 통해 원격 저장소에 합쳐질 경우 
:point_right:  `Merge pull request #PR from 저장소이름/브랜치`

## 위와 같이 기본적으로 생성 되는데 왜 굳이 필요하다고 생각 하냐면요,

저희가 github flow 전략을 취하면서 다음과 같이 merge가 연속적으로 발생합니다. 

`upstream/feature-기능` :point_left: `local/branch` 
- 제목: Merge pull request #PR번호 from greyHairChooseLife/commit_template
- 내용: PR 메시지

`upstream/main` :point_left:  `upstream/feature-기능` 
- 제목: Merge pull request #PR번호 from wanted-pre-onboarding-side-project/setting-commit_template
- 내용: PR 메시지

이렇다 보니 뭐가 어디로 어떻게 merge 됐다는 건지 한눈에 안 들어오더라고요.

## 예시

저희 최근 PR이 커밋 템플릿 적용이잖아요?

`git log` 찍어보면 다음과 같습니다.

```
commit bb69b44133cda29378e575546de90a11a934e965
Merge: 63a2793 8463342
Author: greyHairChooseLife <67201870+greyHairChooseLife@users.noreply.github.com>
Date:   Thu Apr 6 21:30:50 2023 +0900

    Merge pull request #22 from wanted-pre-onboarding-side-project/setting-commit_template
    
    Setting commit template

commit 84633426e8b47ef5fbff93d30833fe86234efbf8
Merge: 63a2793 f108a62
Author: greyHairChooseLife <67201870+greyHairChooseLife@users.noreply.github.com>
Date:   Thu Apr 6 21:25:24 2023 +0900

    Merge pull request #21 from greyHairChooseLife/commit_template
    
    docs: commit Template 파일 생성 및 적용 스크립트

commit f108a62238188f91a61a97f15bbd53d8c3eb89c6
Author: sangyeon kim <greyhairchooselife@gmail.com>
Date:   Thu Apr 6 20:43:15 2023 +0900

    docs: commit Template 파일 생성 및 적용 스크립트

```

`git log --oneline`을 찍으면 더욱 알아보기 힘들어요. 

```
bb69b44 Merge pull request #22 from wanted-pre-onboarding-side-project/setting-commit_template
8463342 Merge pull request #21 from greyHairChooseLife/commit_template
f108a62 docs: commit Template 파일 생성 및 적용 스크립트
```

왜 merge가 두 번 연속인지도 금방 알아보기 어렵고, 제목에 `pr넘버 from 저장소/브랜치`가 필요하진 않다고 봅니다.

## 제안

`upstream/feature-기능` :point_left: `local/branch` 
- 제목
Merge TO upstream/feature-기능 FROM local
- 내용 
첫 줄 : pull request #PR번호 from 저장소이름/브랜치
(한 줄 비우고)
이후 : PR 메시지

`upstream/main` :point_left:  `upstream/feature-기능` 
- 제목
Merge TO upstream/main FROM upstream/feature-기능
- 내용
첫 줄 : pull request #PR번호 from 저장소이름/브랜치
(한 줄 비우고)
이후 : PR 메시지

PR이 승인 되고 merge하려고 하면 `#PR번호 from 저장소이름/브랜치` 가 자동으로 제목 칸에 생성됩니다. 그래서 약간만 수정 하면 돼요.

아까 fetch 받아서 로그 찍어보고 merge가 좌라락 있어서 뭐지.. 하다가 제안 드려봅니다.

**Comment by jiyeon2** [comment]
깃로그를 자세히 보지 않아서 잘 몰랐는데
저렇게 표시되면 머지 커밋 메시지가 어떤 내용인지 알기 어렵네요~

상연님이 제안해주신 내용 좋습니다~ 👍 

지금은 저희가 main브랜치 push시 자동 배포되는 절차를 설정하지 않아서
나중에 생각해 볼 이야기인 듯 하지만
`upstream/main 👈 upstream/feature-기능` 이 하나의 머지가 하나의 배포단위가 될 것으로 보입니다
이 단계에서는 커밋메시지에 배포 버전도 같이 명시하면 어떨까 생각이 들었습니다!

**Comment by greyHairChooseLife** [comment]
@jiyeon2 오, 좋은 의견입니다. 반대편에서 READ의 버전 기록에 해당 `merge commit`을 참조 해 줄 수도 있겠네요.

이 issue를 닫으면서 관련 내용으로 `wiki` 탭에 정리 하고, 이 이슈를 참조 해 두겠습니다.
