### ISSUE TITLE
커밋 컨벤션에 로컬 브랜치 merge 남기지 않기 추가 어때요.

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#26]
merge 종류가 fast-forward랑 3-way가 있는데요,

로컬 개발에서는 무조건 fast-forward만 쓰자는 제안입니다.

다시 말하면 각자 로컬에서 브랜치 관리를 어떻게 하든, 최종적으로 upstream 저장소로 PR을 날릴 때엔 깔끔하게 1줄만 남기자는 것입니다!

만약에 로컬에서 브랜치 나누고 합치고 하느라구 3-way merge가 되더라두 알아서 rebase하고 merge하기로요.

어떠신가요? 

---

혹시 merge 두 종류 구분이 아리송하시면 제가 낼 디코로 설명해드릴게요. 알고 보면 간단해서 1분이면 돼요.

**Comment by jiyeon2** [comment]
항상 merge만 써서 rebase에 대해 이해를 잘 못하고 있어요..
괜찮으시면 내일 fast-forward, 3-way 두가지 merge 설명을 좀 부탁드릴게요!!
