### ISSUE TITLE
.prettier 적용안되는 버그

### ISSUE THREAD

**Issue by chadseok** [wanted-pre-onboarding-side-project/habit-tracker#31]
## 버그 상황

현재 `main`브랜치에 있는 .prettier파일이 적용안되고 있습니다. 

@greyHairChooseLife 님께 미리 얘기를 했던 부분인데 제가 `.prettier`형태면 적용이 안되고 `.prettierrc`여야지 적용이 된다고 말씀드렸는데 @greyHairChooseLife 님이 `.prettier`도 적용이 된다고 얘기하셔서 일단 그 부분에 대한 논의는 마무리가 되었습니다. 

하지만 이번에 제가 작업을 하면서 `.prettier`가 적용이 안되는 것을 직접 확인하였고 수정이 되었으면 합니다

<br>

### 현재 .prettier 상태
- `singleQuote`가 **true**인 상태입니다. 그러므로 prettier 적용시 문자열은 작은 따옴표로 표시되어야 합니다
- 하지만 App.tsx를 prettier 적용시 여전히 큰 따옴표로 표시되고 있습니다 
<img width="408" alt="스크린샷 2023-04-11 오후 3 30 21" src="https://user-images.githubusercontent.com/83488329/231075647-58f9c993-4b1d-4bb6-9e78-8cf57ca45c4a.png">
<img width="834" alt="스크린샷 2023-04-11 오후 3 31 57" src="https://user-images.githubusercontent.com/83488329/231076263-4c8e93ea-ef46-4b91-ad54-ff992caefa23.png">

<br>

### .prettierrc로 바꾸난 후 적용 상태
- 정상적으로 작은 따옴표로 바뀌는 것을 볼 수 있습니다
<img width="469" alt="스크린샷 2023-04-11 오후 3 33 46" src="https://user-images.githubusercontent.com/83488329/231076299-9a19faa1-fc49-4179-a9d5-6e6c6c7f6990.png">
<img width="834" alt="스크린샷 2023-04-11 오후 3 32 49" src="https://user-images.githubusercontent.com/83488329/231076321-bae0762a-abb5-41c0-b6de-1614354cf51d.png">

**Comment by greyHairChooseLife** [comment]
오, 좋은 발견을 하셨네요. :+1: 

[공식 문서](https://prettier.io/docs/en/configuration.html)를 살펴 봐도 `.prettier`를 그냥 쓸 수는 없고 `package.json`의 속성으로 쓸 수는 있네요.

___

>@greyHairChooseLife 님께 미리 얘기를 했던 부분인데 제가 .prettier형태면 적용이 안되고 .prettierrc여야지 적용이 된다고 말씀드렸는데 @greyHairChooseLife 님이 .prettier도 적용이 된다고 얘기하셔서 일단 그 부분에 대한 논의는 마무리가 되었습니다.

글쎄요, 제가 기억하기로는 파일 확장자를 eslint 설정 파일과 일치하도록 `.json`으로 바꾸고 싶다는 것이 주된 말씀이셨던 것 같은데요? 각 파일이 어떤 역할을 하는지 알아보기 쉽고, 유명한 라이브러리나 창환님 본인께서는 그렇게 쓴다고 근거를 말씀하셨지만, 저는 확장자를 바꿔봐야 prettier설정 파일 간의 우선순위만 달라질 뿐이라서 하신 말씀 만으로는 개인적으로 납득 안된다고 했고요.

이 이야기를 하는 것이 무슨 의미가 있을까 싶기는 하지만요. 

그래도 한 가지 다시 떠오르는 것은 프로젝트에 관한 대화나 제안 등은 최대한 이슈와 디스커션을 활용하는 것이 좋겠습니다.

**Comment by chadseok** [comment]
넵 eslint, prettier의 json확장자 통일로 이야기가 시작되었지만 이야기를 나누다가  `.prettier` 다음에 `rc`의 유무에 대해서 제가 질문을 드렸습니다. 그때 `rc`가 확장자 이름 역할을 한다고 하셨고 없어도 된다고 했던 기억이 있습니다

그리고 확장자가 우선순위에 미치는 영향에 대해 조사해보니까 prettier가 내부적으로 cosmiconfig를 따른 다는 것을 알았습니다
https://github.com/cosmiconfig/cosmiconfig#cosmiconfig

여기에 나와있기로는 rc파일의 확장자 없는 설정파일이 확장자가 있는 파일보다 우선된다고 나와있습니다.
저는 저희 프로젝트가 많은 prettier설정파일을 만들고 확장자를 바꾸어 우선순위 조정은 하지 않겠지만 설정파일에 대한 기준점은 잡아야된다고 생각합니다. json을 붙이던 없애던 통일된 기준점이 필요하다고 생각이듭니다

**Comment by greyHairChooseLife** [comment]
>그때 rc가 확장자 이름 역할을 한다고 하셨고 없어도 된다고 했던 기억이 있습니다

리눅스 시스템 하에서는 파일 확장자 자체가 필요하지 않고, `**rc`라는 파일 이름은 보통 어떤 프로그램의 설정 파일 이름으로 쓰인다는 말씀을 드렸습니다. 그 예로 제가 쓰는 vim 프로그램의 설정 파일 이름이 vimrc라거나 bash 프로그램의 설정 파일 이름이 bashrc라고도 말씀드리고요. 확장자의 역할을 한다고 말씀 드린 적은 없습니다.

이름에 'rc'의 유무에 대해서 말씀을 꺼내신 것은 제가 귀담아 듣지 않았는지, 기억이 나지 않는 것인지 모르겠습니다만, 어쨌든 말씀하고자 하시는 바를 분명하게 이해하지 못 한 채로 넘어간 점 사과드려요.

---

>설정파일에 대한 기준점은 잡아야된다고 생각합니다.

무엇으로부터 무엇을 구분하기 위한 기준점인가요?

**Comment by chadseok** [comment]
아닙니다 ㅎㅎ. 궁금해서 여쭤본 것이였습니다. @greyHairChooseLife 님이 물어보신 기준점이라는 것은 위에 설명하였듯이 우선순위에 대한 기준점입니다. 만약 현재 기준으로 prettier와 eslint에 대해 한단계 우선순위가 낮거나 높은 설정파일을 놓는 다면 두개의 확장자가 다르기 때문에 또 다른 확장자나 다른 형태로 설정파일을 만들어야 할 것입니다. 확장자가 일정한 기준없이 막 섞여 있다면  프로젝트 하는 내내 혼동이 올 수 있습니다.

저는 @greyHairChooseLife 님께  **협업하면서 두개의 확장자가 다르면 같이 작업하는 사람이 혼동이 올 수 있다는 점**에 대해서는 어떻게 생각하시는지 알고 싶습니다. 저는 기능상에 문제가 없더라고 같이 협업하는 사람이 혼동이 온다면 이것에 대한 기준점을 잡고 변경을 해봐도 좋다고 생각합니다

그리고 저번에는 제가 말씀드린 "유명 레퍼런스 혹은 대부분의 레포에서는 이렇게 쓰더라"라는 근거는 부족하기 때문에 "굳이 커밋하나를 쓰면서 기능상 아무문제 없는 것을 바꾸어야 할까?" 라고 의문을 제기해주셨는데 이번에 제가 질문드린 '협업하는 사람에게 혼동이 올 수가 있다'에 동의를 하신다면 이번 핫픽스를 하면서 그런 작업을 같이 합쳐서 진행하면 어떨까요? 커밋을 소모하는 문제는 해결할 수 있을 것 같습니다

---

그리고 저는 이번 프로젝트에 뒤늦게 참가하여 프로젝트 설정에 대한 부분을 참가하지 않았습니다. 그래서 저는 이 프로젝트의 eslint, prettier설정을 정확히 어떻게 동작하는지 예측하지 못한 채로 작업을 하고 있습니다. 현재 또 발견한 버그가 있는데 eslint에서 react import관련 룰을 잡아주지  않는 부분입니다. 이런 변수들 때문에 제가 본래 작업에 집중을 못하고 있습니다. 그래서 이런 설정 과정들을 어떤 과정으로 결정하셨는지 제대로 되어있는지가 조금 의문인 상황입니다. 

제가 이렇게 장문의 글을 쓰는 이유는 제가 딴지를 걸고 싶어서 계속 질문을 드리는 것이 아닙니다. 🥲
다만 이런 변수들 때문에 본래 작업에 집중을 못하여서 조금 집요하게 여쭤보고 있습니다. 너그러운 이해 부탁드립니다. 🙂

**Comment by greyHairChooseLife** [comment]
>이번에 제가 질문드린 '협업하는 사람에게 혼동이 올 수가 있다'에 동의를 하신다면 이번 핫픽스를 하면서 그런 작업을 같이 합쳐서 진행하면 어떨까요? 커밋을 소모하는 문제는 해결할 수 있을 것 같습니다

맞습니다. 이렇게 버그 발견 해 주신 덕에 PR도 날려야하니, 연관 되어 개선할 것이 있다면 딱 알맞은 상황인 것 같아요.

>저는 기능상에 문제가 없더라고 같이 협업하는 사람이 혼동이 온다면 이것에 대한 기준점을 잡고 변경을 해봐도 좋다고 생각합니다.

저도 물론 격하게 동의합니다. 

지난 며칠 사이 저희 셋은 코드 1줄 함께 작성하지 않은 채 적어도 20시간은 이야기를 나눈 것 같습니다. 그리고 어찌 보면 작고 사소해 보이는 미묘한 차이들에 대해서도 누구 한 명 귀찮아 하지 않고 적극적으로 논의에 참여했습니다. 

이를 보면 저희 모두 창환님이 말씀 하신 것처럼 협업 과정에 있어 혼란과 혼동이 없어야 한다는 것에 매우 공감한다고 생각합니다.

>현재 또 발견한 버그가 있는데 eslint에서 react import관련 룰을 잡아주지 않는 부분입니다.

버그를 또 발견 해 주셨네요. 이 부분도 이슈를 작성 해 주시면 바로 브랜치를 파도록 하겠습니다. 저 또한 살펴보겠습니다.

>저는 이번 프로젝트에 뒤늦게 참가하여 프로젝트 설정에 대한 부분을 참가하지 않았습니다. 그래서 저는 이 프로젝트의 eslint, prettier설정을 정확히 어떻게 동작하는지 예측하지 못한 채로 작업을 하고 있습니다. 

이 부분은 좀 억울하실 수 있는 부분 같습니다. ㅎㅎ 원래 커밋 히스토리를 통해 이전에 개발 된 내용이 어떤지를 잘 파악 하실 수 있어야 하는데 현재 main브랜치를 보면 기능에 비해 많은 커밋이 있지요. 게다가 어떤 시점에서 어떤 시점으로 roleback하기도 하고요.

다만 변명과 양해를 구해 보자면, 창환님이 합류하시기 전에 지연님과 저도 이 부분(커밋 히스토리를 잘 관리하자)에 나름 신경을 쓴다고 브랜치를 다시 한번 파기도 했고요, 또 한편 앞선 잘못 된 커밋들을 바로 잡는 roleback을 시도한 것도 우리가 공부하고 경험한 성과의 일부라고 여겨 기록을 살려두었습니다.

당장의 커밋 히스토리가 썩 보기 좋지는 않지만.. 그래서 기존 멤버로써 죄송한 마음도 들지만, 이미 개발 된 내용이 무엇인지 파악하는 것 또한 새로운 프로젝트에 참여하는 사람의 책임이기도 할 것 같습니다. git history, issue history, pr history를 살펴 파악 해 주시기 바랍니다. 또 question이슈를 남겨 주신다면 적극적으로 답변 해 보겠습니다. 

참고로 저희가 `CRA` 이후에 작업 한 내용은 commit message template 적용, `eslint`와 `prettier`를 `husky` 라이브러리를 활용해 git hook으로 적용한 것 정도입니다.

(쓸데 없이 첨언하자면, 이와 관련해 저는 꺼내본 적은 없다만 `release` 브랜치를 만들어서 git history를 말끔히 정리한 채로 배포하고 포트폴리오에 보여줄 수도 있겠다는 생각은 했습니다. 다만 이 부분은 프로젝트 매니져의 역할인 것 같기도 하고, 꼼꼼하고 조심히 다뤄야 하는 부분이라 당장은 저도 이렇다 할 제안을 해 보지는 못했습니다.)

>그래서 이런 설정 과정들을 어떤 과정으로 결정하셨는지 제대로 되어있는지가 조금 의문인 상황입니다.

창환님의 합류 전 시점에 결정 된 내용들은 대부분 issue를 활용해 논의하거나 때로는 discord에서 대화하고 적용했습니다.

제대로.. 라면 어떤 뜻인지 모르겠으나 코드, 이슈, PR, 위키 기록을 통해 이해하기 어려운 것이 있다면 question 이슈 또는 디스커션을 발행 해 주시거나 간단한 것은 디코에서 이야기 해 보셔도 좋을 것 같습니다.

>협업하면서 두개의 확장자가 다르면 같이 작업하는 사람이 혼동이 올 수 있다는 점에 대해서는 어떻게 생각하시는지 알고 싶습니다.

eslint 설정파일은 eslint의 설정을 위한 것이고, prettier설정 파일은 prettier를 위한 것인데 둘 사이 무슨 연관이 있어서 확장자가 다를 때 혼동이 올 수 있는지 모르겠습니다.

>제가 이렇게 장문의 글을 쓰는 이유는 제가 딴지를 걸고 싶어서 계속 질문을 드리는 것이 아닙니다. :smiling_face_with_tear:
다만 이런 변수들 때문에 본래 작업에 집중을 못하여서 조금 집요하게 여쭤보고 있습니다. 너그러운 이해 부탁드립니다. :slightly_smiling_face:

걱정 마셔요. 요 며칠 간 제가 느끼는 것은 저희들 모두 서로의 다른 생각들을 이해하기 위해 최선을 다 하는 사람들이라는 것입니다.

좋아서 못사는 연인 간에도 생각이 다르면 싸우기 쉬운데, 저희는 돈도 안 받는 이 프로젝트에 힘들텐데도 얼렁뚱땅 넘어가지 않고 최선을 다 해서 서로를 이해하려고 하고 있잖아요. :+1:

저 또한 제 생각을 쉽고 명확하게 말씀드리려 노력하고 있고, 반대로 여러분의 생각을 이해하려고 노력하지만 잘 해내고만 있진 않은 듯 합니다. 저도 이점 양해 부탁 드려요. :smile:

**Comment by jiyeon2** [comment]
창환님은 작업을 시작하고 싶으신데 
본인이 참여하지 않은 설정에서 문제가 발생하니 많이 답답하셨죠.. 
이슈를 너무 늦게 확인해서 죄송합니다

> 저는 이 프로젝트의 eslint, prettier설정을 정확히 어떻게 동작하는지 예측하지 못한 채로 작업을 하고 있습니다. 현재 또 발견한 버그가 있는데 eslint에서 react import관련 룰을 잡아주지 않는 부분입니다. 이런 변수들 때문에 제가 본래 작업에 집중을 못하고 있습니다. 그래서 이런 설정 과정들을 어떤 과정으로 결정하셨는지 제대로 되어있는지가 조금 의문인 상황입니다.

창환님 합류 전 초기세팅 작업은 아래와 같이 진행되었습니다.
1. cra로 리액트 앱 생성 및 eslint, prettier, husky 설치 => 제가 진행하였습니다
2. eslint, prettier 관련 제가 특정 설정을 사용하지 않아서, 상연님이 사용하시던 설정파일을 그대로 사용하기로 하고 디스코드로 설정파일을 전달받았습니다.
3. 최초 설정시 제가 husky 명령어를 사용하지 않고 .husky 폴더에 바로 파일을 넣어서 pre-commit 훅 등이 제대로 실행되지 않는 문제가 있었습니다
4. 3번의 문제를 해결하기 위해 main 브랜치를 eslint, prettier, husky 설정 전 상태로 되돌렸습니다(cra 사용하여 리액트 앱 생성한 최초 상태로 되돌림)
5. 다시 eslint, prettier, husky 설정하는 과정에서 제가 .prettierrc 파일의 이름을 .prettier로 잘못 추가하였습니다. 순전히 제 실수로 prettier 설정이 적용되지 않는 문제가 발생하였습니다.


**요약**
prettier 설정파일 이름이 현재 main 브랜치에서 .prettier 인 이유는 제가 파일명을 잘못 작성한것 
(상연님이 전달해주신 원본 파일명은 .prettierrc였습니다
최초 설정파일을 main에 적용한 커밋 b71d88ac49338bae28a0662c4dbe827f18e30923 에서 .prettierrc 로 등록되어 있는 것을 확인할 수 있습니다)

**제가 취할 조치사항**
hotfix 브랜치에서 .prettier 설정파일 명을 .prettierrc로 수정하고 pr 올리기 #35 
(창환님이 말씀해주신것처럼 prettierrc로 바꾸면 제대로 동작하는 것을 로컬에서 확인하였습니다)

기타 제 의견
eslint, prettier 설정파일 확장자가 달라도 저같은 경우 헷갈리지 않습니다(설정파일에 대한 지식이 부족하여 기본 설정으로만 사용해왔고, 별도의 설정파일을 사용하지 않았습니다..)
저는 어떤 확장자든 여러분들의 의견에 따르겠습니다!
다만 설정파일 내부 규칙을 바꾸는 경우 코드 전체에 영향이 가므로 논의가 필요하다고 생각합니다

창환님이 언급해주신 
> eslint에서 react import관련 룰을 잡아주지 않는 부분

은 제가 확인을 못했는데 
어떤 룰이 적용되지 않는지 알려주실 수 있을까요?
낮 시간에 제가 들어와서 화면을 보고 이야기하면 이해가 빨랐을텐데
늦게 확인하고서 다시 설명을 요청드려 죄송합니다

길어지는 응답때문에 진이 빠지시겠지만
너그러운 마음으로 알려주시면 감사하겠습니다..
