### ISSUE TITLE
커밋 메시지 템플릿 만들기

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#7]
커밋 컨벤션 이건 어떠신가요? 

뭔가 추가 수정 할 것이 보인다면 짚어주세요.

```
#                       ######################
#                             커밋 컨벤션
#                       ######################
#
# 규칙
#
# 1. 제목은 commit을 설명하는 하나의 구, 절로 완성합니다.
# 2. prefix를 반드시 명시합니다.
# 3. 해당 커밋과 관련 된 고민이나 질문, 그리고 그에 대한 솔루션과 근거를 함께 적어줍니다.
# 4. 필요시 본문 하단에 issue를 link합니다.(이슈 번호로 이슈 link를 생성하고, 앞에 closed를 붙여 이슈를 닫을 수 있습니다.)
#
# prefix 종류
#
#   feat     : 기능 추가, 삭제, 변경 등 기능 관련 - 코드 수정 발생
#   fix      : 오류 개선 혹은 버그 패치 - 코드 수정 발생
#   docs     : 문서화 작업 - 코드 수정 없음
#   test     : test 관련
#   refactor : 코드 리팩토링 ex) 변수명 변경 - 코드 수정 발생
#   style    : 코드 포맷팅, 디자인, 코드 변경이 없는 경우
#   chore    : 빌드 업무 수정, 패키지 매니저 수정
#   etc   : 다른 prefix가 적합하지 않을 경우
```

**Comment by jiyeon2** [comment]
제가 이슈탭을 너무 늦게봤네요.. 죄송합니다!! 
제시해주신 커밋컨벤션과 prefix 모두 좋습니다!

한가지 궁금한 부분이 있는데
> style    : 코드 포맷팅, 디자인, 코드 변경이 없는 경우

여기서 디자인이라 함은 css(스타일) 변경을 포함하나요?
css 변경은 코드 변경인데 style에는 코드 변경이 없는 경우라고 명시되어 있어
상연님은 어떻게 구분하시는지 궁금합니다

css 변경은 코드 수정이 발생하나 기능에 변경은 없으므로 refactor에 해당될까요?

--- 

이전 커밋의 경우 저는 add 라는 prefix에 기능 관련, 패키지 매니저 설치 등을 모두 포함했는데
feat와 chore로 나누는 게 더 의미가 분명해 보이네요!!

앞으로는 이 컨벤션에 따라 커밋메시지 작성해보겠습니다

**Comment by greyHairChooseLife** [comment]
style부분은 확실히 명확하지 않은 것 같습니다.

>style: css 등 디자인
으로 변경토록 하겠습니다.
