### ISSUE TITLE
git history 관리와 관련 컨벤션이 필요 해 보입니다.

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#8]
관련 PR #4 

리뷰 할 때는 미처 생각하지 못했는데요, 작업하고 커밋 하려다 보니 git history 관리가 안된 것 같더라구요. 그러고보니 아까 디코로 이야기 중에 이 말씀을 살짝 하셨던 것 같기도 한데... 제가 하시는 말씀을 부주의하게 들었나 봐요. 사과드립니다.

## 문제라고 생각하는 것들

현재 organization의 dev에 merge된 커밋 히스토리는 다음과 같은데요,

```
//  git log --oneline
b71d88a Merge pull request #4 from wanted-pre-onboarding-side-project/setting
e3295f7 Merge branch 'setting' of https://github.com/wanted-pre-onboarding-side-project/habit-tracker into setting
c12b6d8 remove : 사용하지 않는 설정 삭제
6f22c1a remove : 사용하지 않는 패키지 삭제
7e68959 remove : 사용하지 않는 패키지 삭제
3805c3c add : eslint, prettier setting
698196e Initialize project using Create React App
```

#### 첫째 문제,

여기에서 remove prefix가 달려 있는 것들은 커밋을 **수정** 해야지 **추가** 해서는 안된다고 생각합니다.

만약, 과거 PR이 merge 되면서 생성 된 요소들(파일이든 코드든)에 관한 것이라면 **그땐 그것이 있어야 했지만, 지금은 없어야 하는 이유**가 중요 할 수 있다고 생각합니다. 그러니까 commit history에 남겨둘 정보가 된다고 생각해요.

하지만 이번처럼 PR 된 내용을 리뷰하는 과정에서 수정 될 내용이 발생했다면, 있던 것을 remove 한다기보단 애초에 없어야 한다는 뜻입니다.

#### 둘째 문제,

저희가 디코로 논의 할 때 각자의 로컬 개발 환경의 브랜치 관리는 스스로 하되, PR을 날릴 때에는 정해진 branch로 날리자 했었습니다. 그런데 아래와 같은 커밋은 아마도 지연님의 로컬 개발환경에서 브랜치를 분리하여 사용하는 과정에서 생성 된 듯 합니다.

`e3295f7 Merge branch 'setting' of https://github.com/wanted-pre-onboarding-side-project/habit-tracker into setting`

각자 관리하기로 한 로컬 브랜치의 merge 내역이라는 정보가 organization의 공동 저장소에도 기록 되어야 할 정보는 아니라고 생각됩니다.

#### 셋째 문제,

`b71d88a Merge pull request #4 from wanted-pre-onboarding-side-project/setting`

이 커밋은 PR이 merge 되었다는 표시를 하는 것이기 때문에 필요한 커밋 같습니다. 다만 이것은 자동 생성 된 것이고 뜯어보자면
Merge / pull request #PR아이디 /  from 저장소/브랜치
인데요, 

근데 왜 저게 `setting`브랜치로 뜨는지 의문이네요. 저희가 organizatin 저장소의 브랜치는 일단 main과 dev를 두고, dev에다가 PR날리기로 했었잖아요? 실제로 아까 dev 브랜치에 PR날리시고 저도 리뷰했고요.  그러면 이 커밋 메시지 끝에 dev 브랜치라고 붙어야 하는 것으로 아는데... 

이 부분은 저희가 좀 공부를 하거나 테스트를 해서 확실히 하면 좋을 것 같습니다. 혹시 잘 알고 계신다면 공유 해 주시면 감사하겠습니다!

## 제안

1. 저는 이참에 이미 merge 된 PR을 아예 롤백하고 다시 PR을 날려보는 경험을 해 보는 것도 좋을 것 같습니다. 위의 문제에 동의하신다면 이 방법으로 해결하는 것이 좋아 보이기도 하고요.

2. PR 메시지에도 어떤.. 템플릿이나 작성해야 하는 기본 항목들을 두면 좋을 것 같습니다. 그리고 이 PR메시지가 커밋 히스토리에 포함되면 좋을 것 같습니다.

왜냐면 각 PR을 리뷰하는 단계에서는 커밋 메시지 하나하나를 살펴보지만, 만약 나중에 저희가 리팩토링을 한다거나 또는 제 3자가 어떤 프로젝트를 대강 살펴볼 때는 PR 기록 정도만 살펴 볼 것 같거든요. 

그 때 github 사이트에 들어와서 PR탭을 볼 수도 있고, 또는 터미널에서 git log 중 merge pull request 내역만 뽑아서 살펴 볼 수도 있을 것 같습니다. 이런 리뷰어들은 이제.. 저희의 포트폴리오를 살펴 볼 누군가를 배려하는 것이기도 하고, 취업해서 일을 하게 됐을 때 동료들을 배려하는 것이기도 하니까요.

---

제가 문제라고 생각하는 것을 지연님도 문제라고 생각하시는지, 다른 생각은 없으신지, 제안 드리는 것들은 어찌 생각하시는지 의견 부탁드려요.

**Comment by jiyeon2** [comment]
상연님이 언급해주신 세가지 문제에 모두 동의합니다

제가 git history에 대한 이해가 부족하여 불필요한 
커밋메시지를 병합한다든가 하는 처리를 하지 못했습니다..

이후 프로젝트를 확인할 사람을 위해 pr도 정리해야 한다는 인식을 못했어요 좋은 생각입니다!

저도 git history관리 방식을 잘 알지 못해서 
상연님의 제안대로 pr 롤백하고 다시 날려봤으면 합니다

제가 또 main에 pr 합치고 revert해서 또 pr 내역이 더러워졌는데 죄송합니다..

**Comment by jiyeon2** [comment]
제안 2 관련
[github pr template ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)을 만들어 동일한 구조의 pr 메시지 작성하면 어떨까요?
간단하게 적용할 수 있을듯 합니다

참고한 블로그 글 : [헤이딜러 개발팀 모두가 행복한 개발/PR관리 방법 7가지](https://medium.com/prnd/%ED%97%A4%EC%9D%B4%EB%94%9C%EB%9F%AC-%EA%B0%9C%EB%B0%9C%ED%8C%80-%EB%AA%A8%EB%91%90%EA%B0%80-%ED%96%89%EB%B3%B5%ED%95%9C-%EA%B0%9C%EB%B0%9C-pr%EA%B4%80%EB%A6%AC-%EB%B0%A9%EB%B2%95-7%EA%B0%80%EC%A7%80-1d4cd5d091f0)

**Comment by greyHairChooseLife** [comment]
pr템플릿 만드는 거 좋다고 생각합니다. 커밋 메시지 보다 더 신경 써서 작성해야 할 것 같긴 한데, 막상 쓰려면 커밋 메시지보다 훨씬 범위가 넓어서 막막하기도 하더라구요.

근데 지연님은 pr을 터미널에서 하시나요 아니면 깃헙 사이트에서 하시나요?

**Comment by jiyeon2** [comment]
> 근데 지연님은 pr을 터미널에서 하시나요 아니면 깃헙 사이트에서 하시나요?

저는 깃헙 사이트에서 합니다! 명령어를 잘 못써서요..

**Comment by greyHairChooseLife** [comment]
저도 아직 터미널에선 안해봤어요! 사진도 넣고 하느라 이건 github에서 하는게 더 편할 것 같네요. 링크 해 주신 것 봐두 여기 사이트 기준이고요. 

pr 템플릿 적용 해 보죠!  TODO로 바꾸겠습니다.
