### ISSUE TITLE
public/index.html에 메타데이터 등 관리 해 볼까요?

### ISSUE THREAD

**Issue by greyHairChooseLife** [wanted-pre-onboarding-side-project/habit-tracker#9]
타이틀 수정하려고 `public/index.html` 파일에 들어가 봤는데, 
```
    <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
```

요런 내용이 있더라고요. 이걸 어찌 해 본 경험은 없는데, 어떻게 한번 신경 써 보는 게 좋을까요?

**Comment by jiyeon2** [comment]
프로그레시브 웹 앱 설정파일 같은건가 보네요! 이름만 들어봐서 찾아봤는데

[프로그레시브 웹 앱](https://web.dev/what-are-pwas/) : 브라우저 탭 대신 독립 실행형 창에서 실행되는 웹 애플리케이션

이라고 해요! 
이 서비스를 앱처럼 간단하게 켜서 쓸 수 있으면 좋겠다고 생각하던 참인데
프로그레시브 웹 앱도 공부해보고 이 프로젝트에 적용하면 좋을거같아요!! :+1:

**Comment by greyHairChooseLife** [comment]
> [프로그레시브 웹 앱](https://web.dev/what-are-pwas/) : 브라우저 탭 대신 독립 실행형 창에서 실행되는 웹 애플리케이션

저는 그냥 검색엔진 봇이랑 연관된 메타 정보인 줄 알았는데, 더 좋은거였네요.  TODO로 바꿔둡니다.
